[pytest]
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:Warning
    ignore:Setting the shape on a NumPy array has been deprecated in NumPy 2.5.:DeprecationWarning
    ignore:`sklearn.utils.parallel.delayed` should be used.*:UserWarning
